name: Auto Generate Links
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run link.py
        run: python3 links.py
      - name: Commit new link changes
        run: |
          git config --global user.name 'CFE Auto'
          git config --global user.email 'codingentrepreneurs@users.noreply.github.com'
          git checkout "${GITHUB_REF:11}"
          git commit -am "Automated link generation"
          git push
